### PR TITLE
Added CategoryAttribute to properties of actions and behaviors

### PR DESCRIPTION
**Pull request by xperiandri**
Added CategoryAttribute to properties of actions and behaviors.
Now everything is OK, you should not have any problems with merge.

### CODE REVIEW

**Comment by pedrolamas** [comment]
I appreciate the work here, but I can't merge these files as apparently you changed some of the files "new line" style, breaking completely the Diff... just check the Diff above and you'll see what I mean!

**Comment by xperiandri** [comment]
Sorry.
What is the current line ending style in the project?

**Comment by xperiandri** [comment]
I've just looked at the diff and it is OK.
In my request all line endings are Unix styled. Should be the same as in cimbalino/master

**Comment by pedrolamas** [comment]
Seems I'm missing the .gitattributes file here... but check the GitHub Diff for your commits above, think that will help clear things out.

**Comment by xperiandri** [comment]
Yes, I accidentally changed style to Windows for some files and than back to Unix.
So, how to deal with it so you will apply my pull request?
Do you have any suggestions?

**Comment by pedrolamas** [comment]
Yeah, a lot of work to fix it... but it's in now! :)

**Comment by xperiandri** [comment]
Thank you, @PedroLamas!
Sorry for extra work, nevertheless this are useful changes.

**Comment by pedrolamas** [comment]
No problem, and thank you for contributing! :)

**Pull request merged**
